# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stool',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
    ]
